package alpaca
package internal
package lexer

import scala.annotation.tailrec
import scala.util.matching.Regex
import scala.NamedTuple.{AnyNamedTuple, NamedTuple}

/**
 * The result of compiling a lexer definition.
 *
 * This abstract class represents a compiled lexer that can tokenize input.
 * It is generated by the `lexer` macro and provides methods to access tokens
 * and perform tokenization.
 *
 * @tparam Ctx the global context type
 */
transparent abstract class Tokenization[Ctx <: LexerCtx](
  using copy: Copyable[Ctx], // todo: unused
  betweenStages: BetweenStages[Ctx],
) extends Selectable:
  type LexemeRefinement <: Lexeme[?, ?]

  /** List of all tokens defined in this lexer, including ignored tokens. */
  def tokens: List[Token[?, Ctx, ?]]

  /**
   * Provides dynamic access to tokens by name.
   *
   * This allows accessing tokens using dot notation, e.g., `myLexer.PLUS`.
   *
   * @param fieldName the token name
   * @return the token definition
   */
  def selectDynamic(fieldName: String): DefinedToken[?, Ctx, ?] { type LexemeTpe = LexemeRefinement }

  /**
   * Tokenizes the input character sequence.
   *
   * Processes the input from start to finish, matching tokens and building
   * a list of lexems. Throws a RuntimeException if an unexpected character
   * is encountered.
   *
   * @param input the input to tokenize
   * @param empty implicit Empty instance to create the initial context
   * @return a list of lexems representing the tokenized input
   */
  final def tokenize(
    input: CharSequence,
  )(using empty: Empty[Ctx],
  ): (ctx: Ctx, lexemes: List[Lexeme[?, ?] & LexemeRefinement]) =
    @tailrec def loop(
      globalCtx: Ctx,
    )(
      acc: List[Lexeme[?, ?] & LexemeRefinement],
    ): List[Lexeme[?, ?] & LexemeRefinement] =
      globalCtx.text.length match
        case 0 =>
          acc.reverse // todo: make it not reversed
        case _ =>
          val m = compiled.findPrefixMatchOf(globalCtx.text) getOrElse {
            // todo: custom error handling https://github.com/halotukozak/alpaca/issues/21
            throw new RuntimeException(s"Unexpected character: '${globalCtx.text.charAt(0)}'")
          }
          val token = tokens.find(token => m.group(token.info.regexGroupName) ne null) getOrElse {
            throw new AlgorithmError(s"$m matched but no token defined for it")
          }
          betweenStages(token, m, globalCtx)
          val lexem = List(token).collect:
            case _: DefinedToken[?, Ctx, ?] => globalCtx.lastLexeme.nn.asInstanceOf[Lexeme[?, ?] & LexemeRefinement]
          loop(globalCtx)(lexem ::: acc)

    val initialContext = empty()
    initialContext.text = input
    (initialContext, loop(initialContext)(Nil))

  /** The compiled regex that matches all defined tokens. */
  protected def compiled: Regex

extension (input: CharSequence)
  private[alpaca] def from(pos: Int): CharSequence = input match
    case lfr: LazyReader => lfr.from(pos)
    case _ => input.subSequence(pos, input.length)
