package alpaca
package internal
package lexer

import alpaca.internal.lexer.ErrorHandling.Strategy
import alpaca.internal.lexer.regex.TokenMatcher

import scala.NamedTuple.{AnyNamedTuple, NamedTuple}
import scala.annotation.publicInBinary
import scala.collection.mutable

/**
 * The result of compiling a lexer definition.
 *
 * This abstract class represents a compiled lexer that can tokenize input.
 * It is generated by the `lexer` macro and provides methods to access tokens
 * and perform tokenization.
 *
 * @tparam Ctx the global context type
 */
transparent abstract class Tokenization[Ctx <: LexerCtx](
  using betweenStages: OnTokenMatch[Ctx],
  errorHandling: ErrorHandling[Ctx],
  empty: Empty[Ctx],
) extends Selectable:
  type Fields <: AnyNamedTuple
  type LexemeFields <: AnyNamedTuple
  final type Lexeme = alpaca.internal.lexer.Lexeme[?, ?] withFields LexemeFields

  /** List of all tokens defined in this lexer, including ignored tokens. */
  @publicInBinary
  private[alpaca] def tokens: List[Token[?, Ctx, ?]]

  /**
   * Provides dynamic access to tokens by name.
   *
   * This allows accessing tokens using dot notation, e.g., `myLexer.PLUS`.
   *
   * @param fieldName the token name
   * @return the token definition
   */
  def selectDynamic(fieldName: String): Token[?, Ctx, ?]

  /**
   * Tokenizes the input character sequence.
   *
   * Processes the input from start to finish, matching tokens and building
   * a list of lexemes. Throws a RuntimeException if an unexpected character
   * is encountered.
   *
   * @param input the input to tokenize
   * @return a tuple of (ctx, lexemes) where ctx is the final lexer context and lexemes is the list of matched tokens
   */
  final def tokenize(input: CharSequence): (ctx: Ctx, lexemes: List[Lexeme]) =
    val globalCtx = empty()
    globalCtx.text = OffsetCharSequence(input)

    val acc = mutable.ListBuffer.empty[Lexeme]

    while !globalCtx.text.isEmpty do
      val (token, matched) = matcher.matchAt(globalCtx.text, 0) match
        case Some((priority, end)) if end > 0 =>
          val matchedStr = globalCtx.text.subSequence(0, end).toString
          globalCtx.lastRawMatched = matchedStr
          val found = tokensArray(priority)
          globalCtx.text = globalCtx.text.from(end)
          (found, matchedStr)

        case _ =>
          errorHandling(globalCtx) match
            case Strategy.Throw(ex) =>
              throw ex

            case Strategy.IgnoreToken =>
              matcher.findFirst(globalCtx.text, 1) match
                case Some((firstMatching, _, _)) =>
                  val matchedStr = globalCtx.text.subSequence(0, firstMatching).toString
                  globalCtx.lastRawMatched = matchedStr
                  globalCtx.text = globalCtx.text.from(firstMatching)
                  (RecoveredToken(matchedStr), matchedStr)
                case None =>
                  val matchedStr = globalCtx.text.charAt(0).toString
                  globalCtx.lastRawMatched = matchedStr
                  globalCtx.text = globalCtx.text.from(1)
                  (RecoveredToken(matchedStr), matchedStr)

            case Strategy.IgnoreChar =>
              val matchedStr = globalCtx.text.charAt(0).toString
              globalCtx.lastRawMatched = matchedStr
              globalCtx.text = globalCtx.text.from(1)
              (RecoveredToken(matchedStr), matchedStr)

            case Strategy.Stop =>
              globalCtx.text = ""
              (null, null)

      if token != null && matched != null then
        betweenStages(token, matched, globalCtx)
        if token.isInstanceOf[DefinedToken[?, Ctx, ?]] then acc.addOne(globalCtx.lastLexeme.nn.asInstanceOf[Lexeme])

    (globalCtx, acc.toList)

  /** Compiled token-matcher; built at macro time. */
  protected def matcher: TokenMatcher

  private lazy val tokensArray: Vector[Token[?, Ctx, ?]] = tokens.toVector

extension (input: CharSequence)
  private[alpaca] def from(pos: Int): CharSequence = input match
    case ocs: OffsetCharSequence => ocs.from(pos)
    case lfr: LazyReader => lfr.from(pos)
    case _ => input.subSequence(pos, input.length)
