package alpaca.lexer

import alpaca.core.{Copyable, Empty}
import alpaca.lexer.context.{AnyGlobalCtx, Lexem}

import scala.annotation.tailrec
import scala.util.matching.Regex

/**
 * The result of compiling a lexer definition.
 *
 * This abstract class represents a compiled lexer that can tokenize input.
 * It is generated by the `lexer` macro and provides methods to access tokens
 * and perform tokenization.
 *
 * @tparam Ctx the global context type
 */
abstract class Tokenization[Ctx <: AnyGlobalCtx: {Copyable as copy, BetweenStages as betweenStages}]
  extends Selectable {

  // protected def compiled: Regex

  private lazy val compiled: Regex =
    // todo: consider some quoting somewhere someday
    tokens.view.map(_.info).map(info => s"(?<${info.regexGroupName}>${info.pattern})").mkString("|").r

  /** List of all tokens defined in this lexer, including ignored tokens. */
  def tokens: List[Token[?, Ctx, ?]]

  /** Map of token names to their definitions for dynamic access. */
  def byName: Map[String, DefinedToken[?, Ctx, ?]] // todo: reconsider if selectDynamic should be implemented with PM

  /**
   * Provides dynamic access to tokens by name.
   *
   * This allows accessing tokens using dot notation, e.g., `myLexer.PLUS`.
   *
   * @param fieldName the token name
   * @return the token definition
   */
  def selectDynamic(fieldName: String): DefinedToken[?, Ctx, ?] =
    byName(scala.reflect.NameTransformer.decode(fieldName))

  /**
   * Tokenizes the input character sequence.
   *
   * Processes the input from start to finish, matching tokens and building
   * a list of lexems. Throws a RuntimeException if an unexpected character
   * is encountered.
   *
   * @param input the input to tokenize
   * @param empty implicit Empty instance to create the initial context
   * @return a list of lexems representing the tokenized input
   */
  final def tokenize(input: CharSequence)(using empty: Empty[Ctx]): List[Lexem[?, ?]] = {
    @tailrec def loop(globalCtx: Ctx)(acc: List[Lexem[?, ?]]): List[Lexem[?, ?]] =
      globalCtx.text.length match
        case 0 =>
          acc.reverse
        case _ =>
          val m = compiled.findPrefixMatchOf(globalCtx.text) getOrElse {
            // todo: custom error handling https://github.com/halotukozak/alpaca/issues/21
            throw new RuntimeException(s"Unexpected character: '${globalCtx.text.charAt(0)}'")
          }
          val token = tokens.find(token => m.group(token.info.regexGroupName) ne null) getOrElse {
            throw new AlgorithmError(s"$m matched but no token defined for it")
          }
          betweenStages(token, m, globalCtx)
          val lexem = List(token).collect { case _: DefinedToken[?, Ctx, ?] => globalCtx.lastLexem }
          loop(globalCtx)(lexem ::: acc)

    val initialContext = empty()
    initialContext.text = input
    loop(initialContext)(Nil)
  }
}

extension (input: CharSequence)
  private def from(pos: Int): CharSequence = input match
    case lfr: LazyReader => lfr.from(pos)
    case _ => input.subSequence(pos, input.length)
